# Generated by Django 4.2.11 on 2026-03-28 17:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=api.models.custom_user_directory_path),
        ),
    ]
