# Generated by Django 4.2.11 on 2026-03-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_document_user_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Eventuale errore del task OCR', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In Coda'), ('PROCESSING', 'In Elaborazione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=20),
        ),
    ]
